### ISSUE TITLE
UnspecifiedCoreConfig naming may be incorrect

### ISSUE THREAD

**Issue by Valve** [machinio/solrb#17]
[3] pry(Solr::Support::UrlHelper)> Solr.current_core_config
=> #<Solr::CoreConfiguration::UnspecifiedCoreConfig:0x00007fcedb45a400 @default=false, @fields={}, @name=nil>

This happens when I use a URL to configure Solrb. In that case it says "Unspecified Core Config".

This naming is incorrect I think. It's not possible to work with solr w/out specifying a core. I did specify the core through the URL, so shouldn't say "unspecified".

**Comment by SeTeM** [comment]
Well, it's unspecified in terms of Solrb: you didn't define core via its configuration block.
What other name do you prefer for cases like this one? `UnspecifiedCoreConfig` was the best name I've found.

**Comment by Valve** [comment]
> you didn't define core via its configuration block.
But I don't need to, I can use a URL for that. 

Vlad, you've gotta deal with the fact that a URL in env is a valid way of using this gem :)

**Comment by Valve** [comment]
don't forget that unconfigured fields are passed through, so if I'm using field names directly, I don't need a configuration block at all.

**Comment by SeTeM** [comment]
Let's change its name to a name that indicates it uses a URL from `ENV['SOLR_URL']`:
`EnvSolrUrlCoreConfig` or `EnvUrlCoreConfig`.
Which one do you like?

**Comment by Valve** [comment]
good idea, let's use latter
