### ISSUE TITLE
Support multiple cores in configuration

### ISSUE THREAD

**Issue by Valve** [machinio/solrb#30]
Currently it's only possible to define a single core in configuration:

```ruby
Solr.configure do |config|
   config.define_core(name: :listings_en) do |f|
     ...
   end
end
```

However there can be situations when it's necessary to define multiple cores at once, i.e. several cores with identical configurations.

Example:

```ruby
Solr.configure do |config|
   config.define_cores(names: %w[listings_en listings_pt listings_es] ) do |f|
     ...
   end
end
```

This configuration type should allow to query different cores and all these core configurations should efficiently reuse the configuration values. That is, there should be only one set of fields in memory, but they should be linked to multiple core names.

@SeTeM @drnluz

**Comment by SeTeM** [comment]
Why don't you use code like this one?
```ruby
%w[listings_en listings_pt listings_es].each do |core_name|
  config.define_cores(name: core_name) do |f|
  end
end
```
Also, don't cores have different configurations for text fields `text_en`, `text_fr`, etc?

**Comment by Valve** [comment]
It's only when the cores have identical configuration, only for those cases.
I can just iterate, it's a small memory-oriented improvement.
